In [70]:
%matplotlib inline

import pandas as pd
import seaborn as sns
import os
import glob
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind

plt.rc('font', size = 8)
plt.rc('font', family='sans serif')
plt.rcParams['pdf.fonttype']=42
plt.rcParams['ps.fonttype']=42
plt.rcParams['legend.frameon']=False
sns.set_style("ticks")

In [71]:
pfp = '/home/ngr4/project/edge_feat/results'

In [88]:
df = pd.read_csv(os.path.join(pfp,'exp_200604.csv'))
x = df.loc[(df['dataset']=='liao') & (df['model']=='GAT_transformer_mlp_batch') & (df['task']=='ycondition'),'acc_test'].astype(float)
y = df.loc[(df['dataset']=='liao') & (df['model']=='GAT') & (df['task']=='ycondition'),'acc_test'].astype(float)

In [83]:
# liao
x = df.loc[(df['dataset']=='liao') & (df['model']=='GCN') & (df['task']=='ycondition'),'acc_test'].astype(float)
print('{:.2f} ({:.2f}-{:.2f})'.format(100*x.mean(), 100*(x.mean()-1.96*x.std()), 100*(x.mean()+1.96*x.std())))

89.26 (89.06-89.47)

In [87]:
# hbec
x = df.loc[(df['dataset']=='hbec') & (df['model']=='GCN_transformer_mlp_batch') & (df['task']=='yinftime'),'acc_test'].astype(float)
print('{:.2f} ({:.2f}-{:.2f})'.format(100*x.mean(), 100*(x.mean()-1.96*x.std()), 100*(x.mean()+1.96*x.std())))

81.61 (79.34-83.87)

In [93]:
# scni
# hbec
x = df.loc[(df['dataset']=='scni*') & (df['model']=='GAT') & (df['task']=='yms'),'acc_test'].astype(float)
print('{:.2f} ({:.2f}-{:.2f})'.format(100*x.mean(), 100*(x.mean()-1.96*x.std()), 100*(x.mean()+1.96*x.std())))

73.03 (72.22-73.83)

In [90]:
df

,dataset,model,task,batch_size,acc_test,loss_test,<acc>_val,<loss>_val,<acc>_train,<loss>_train
0,scnd,GAT,ygenotime,256.0,0.4346,1.6036,0.5183,1.3176,0.5697,1.1877
1,scnd,GAT,ygenotime,256.0,0.4346,1.8031,NaN,NaN,NaN,NaN
2,scnd,GAT,ygenotime,256.0,0.4355,1.6814,NaN,NaN,NaN,NaN
3,scnd,GAT,ygenotime,256.0,0.4247,1.7885,NaN,NaN,NaN,NaN
4,scnd,GAT,yctype,256.0,0.982,0.0544,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
70,scni*,GCN_transformer_mlp_batch,yms,256.0,NaN,NaN,NaN,NaN,NaN,NaN
71,scni*,GAT_transformer_mlp_batch,yms,256.0,NaN,NaN,NaN,NaN,NaN,NaN
72,scni*,GAT_transformer_mlp_batch,yms,256.0,NaN,NaN,NaN,NaN,NaN,NaN
73,scni*,GAT_transformer_mlp_batch,yms,256.0,NaN,NaN,NaN,NaN,NaN,NaN
74,*metrics reported on best epoch of val set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN